import 'dart:convert';
import 'dart:typed_data';

/// Gemma's byte-fallback BPE tokenizer, reading the packed artifact.
///
/// The device has to tokenize the query, because the query is the one thing
/// that cannot be embedded ahead of time. Gemma's own `tokenizer.json` is
/// 33 MB of JSON with 262,144 vocabulary entries — parsing that at launch on a
/// 6 GB phone is not affordable, and almost all of it is dead weight for
/// encoding.
///
/// BPE only needs strings for its very first step. Once each character has
/// become an id, every merge is a pair of ids producing a third, so the packed
/// artifact pre-resolves the merge table to ids and ships only the 19,227
/// single-character entries. Everything after the first loop is integer work.
///
/// This is a second implementation of an algorithm whose output is invisible:
/// a wrong subword split does not throw, it produces a perfectly plausible
/// vector in the wrong place, and retrieval silently gets worse. That is why
/// `test/services/gemma_tokenizer_test.dart` checks every id against a fixture
/// generated by the same Python code that embedded the shipped passages.
///
/// Built by `python -m survive_rag pack --tokenizer <tokenizer.json>`.
class GemmaTokenizer {
  GemmaTokenizer._({
    required Map<String, int> chars,
    required Int64List keys,
    required Int32List ranks,
    required Int32List results,
    required this.bos,
    required this.eos,
    required this.byteBase,
  }) : _chars = chars,
       _keys = keys,
       _ranks = ranks,
       _results = results,
       _mask = keys.length - 1;

  static const List<int> _magic = [0x47, 0x42, 0x50, 0x45]; // "GBPE"
  static const int formatVersion = 1;

  /// U+2581, the marker Gemma's normalizer substitutes for every space.
  static const String _spaceMarker = '▁';

  /// Longest token sequence fed to the encoder. A query never approaches this;
  /// the cap exists so a pasted wall of text cannot stall the isolate.
  static const int maxTokens = 512;

  final Map<String, int> _chars;

  /// Open-addressed table of `(left << 32) | right` merge keys, `-1` when
  /// empty. A `Map<int, int>` of half a million entries costs far more in
  /// boxed objects than three typed arrays.
  final Int64List _keys;
  final Int32List _ranks;
  final Int32List _results;
  final int _mask;

  final int bos;
  final int eos;

  /// Id of `<0x00>`; the token for byte `n` is `byteBase + n`.
  final int byteBase;

  /// Parse a packed tokenizer.
  ///
  /// Throws [FormatException] when the magic or version is unrecognised,
  /// rather than reading a later format as if it were this one.
  factory GemmaTokenizer.parse(ByteData data) {
    for (var i = 0; i < _magic.length; i++) {
      if (data.getUint8(i) != _magic[i]) {
        throw const FormatException('not a packed Gemma tokenizer');
      }
    }
    int u32(int at) => data.getUint32(at, Endian.little);

    final version = u32(4);
    if (version != formatVersion) {
      throw FormatException('unsupported packed tokenizer version $version');
    }
    final charCount = u32(8);
    final mergeCount = u32(12);
    final bos = u32(16);
    final eos = u32(20);
    final byteBase = u32(28);
    final blobLength = u32(32);

    var at = 36;
    final offsets = Uint32List(charCount + 1);
    for (var i = 0; i <= charCount; i++) {
      offsets[i] = u32(at + i * 4);
    }
    at += (charCount + 1) * 4;

    final blob = data.buffer.asUint8List(data.offsetInBytes + at, blobLength);
    at += blobLength;

    final chars = <String, int>{};
    for (var i = 0; i < charCount; i++) {
      chars[utf8.decode(blob.sublist(offsets[i], offsets[i + 1]))] = u32(
        at + i * 4,
      );
    }
    at += charCount * 4;

    var capacity = 1;
    while (capacity < mergeCount * 2) {
      capacity <<= 1;
    }
    final keys = Int64List(capacity)..fillRange(0, capacity, -1);
    final ranks = Int32List(capacity);
    final results = Int32List(capacity);
    final rightAt = at + mergeCount * 4;
    final resultAt = rightAt + mergeCount * 4;

    for (var i = 0; i < mergeCount; i++) {
      final key = (u32(at + i * 4) << 32) | u32(rightAt + i * 4);
      var slot = _slotFor(key, capacity - 1);
      while (keys[slot] != -1) {
        slot = (slot + 1) & (capacity - 1);
      }
      keys[slot] = key;
      ranks[slot] = i;
      results[slot] = u32(resultAt + i * 4);
    }

    return GemmaTokenizer._(
      chars: chars,
      keys: keys,
      ranks: ranks,
      results: results,
      bos: bos,
      eos: eos,
      byteBase: byteBase,
    );
  }

  /// Fibonacci hashing, which spreads the low bits that adjacent ids share.
  static int _slotFor(int key, int mask) => (key * 0x9E3779B97F4A7C15) & mask;

  /// Slot holding [key], or `-1`.
  int _find(int key) {
    var slot = _slotFor(key, _mask);
    while (true) {
      final found = _keys[slot];
      if (found == key) return slot;
      if (found == -1) return -1;
      slot = (slot + 1) & _mask;
    }
  }

  /// Encode [text] to token ids, wrapped in `<bos>` and `<eos>`.
  ///
  /// Gemma's normalizer replaces every space with U+2581 and its pre-tokenizer
  /// then splits on a space that no longer occurs, so the whole string reaches
  /// BPE as one piece — there is no word-boundary pass to reproduce.
  ///
  /// Characters outside the vocabulary fall back to their UTF-8 bytes. That is
  /// what stops Devanagari and emoji collapsing to `<unk>` and stripping a
  /// query of the words it was asking about.
  List<int> encode(String text) {
    final ids = <int>[];
    for (final rune in text.replaceAll(' ', _spaceMarker).runes) {
      final char = String.fromCharCode(rune);
      final known = _chars[char];
      if (known != null) {
        ids.add(known);
      } else {
        ids.addAll(utf8.encode(char).map((b) => byteBase + b));
      }
      if (ids.length >= maxTokens - 2) break;
    }

    while (ids.length > 1) {
      var bestRank = -1;
      var at = -1;
      for (var i = 0; i < ids.length - 1; i++) {
        final slot = _find((ids[i] << 32) | ids[i + 1]);
        if (slot < 0) continue;
        final rank = _ranks[slot];
        if (at < 0 || rank < bestRank) {
          bestRank = rank;
          at = i;
        }
      }
      if (at < 0) break;
      ids[at] = _results[_find((ids[at] << 32) | ids[at + 1])];
      ids.removeAt(at + 1);
    }
    return [bos, ...ids, eos];
  }
}
