/// Conducts the 5-question situation assessment interview.
///
/// Questions are hardcoded Dart strings — NOT generated by the LLM.
/// This makes the interview:
/// - Deterministic (no hallucinated questions)
/// - Instant (no inference during question phase)
/// - Reliable (works even if model is still loading)
///
/// After all answers are collected, [buildRawDescription] assembles them
/// into a free-text summary for the LLM to extract structured [Situation] JSON.
class SituationAssessor {
  static const questions = [
    AssessmentQuestion(
      id: 'environment',
      text: 'Where are you right now?',
      hint: 'e.g. jungle, desert, city, mountain, coastal area',
    ),
    AssessmentQuestion(
      id: 'injuries',
      text: 'Are you or anyone with you injured? If so, describe briefly.',
      hint: 'e.g. broken leg, deep cut, no injuries',
    ),
    AssessmentQuestion(
      id: 'resources',
      text: 'What do you currently have with you?',
      hint: 'e.g. water, food, fire starter, knife, phone, nothing',
    ),
    AssessmentQuestion(
      id: 'companions',
      text: 'How many other people are with you?',
      hint: 'Enter 0 if alone',
    ),
    AssessmentQuestion(
      id: 'goal',
      text: 'What is your immediate goal?',
      hint: 'e.g. find shelter, get medical help, escape area, signal for rescue',
    ),
  ];

  final Map<String, String> _answers = {};
  int _currentIndex = 0;

  bool get isDone => _currentIndex >= questions.length;
  AssessmentQuestion? get currentQuestion =>
      isDone ? null : questions[_currentIndex];
  int get progress => _currentIndex;
  int get total => questions.length;

  void recordAnswer(String answer) {
    if (isDone) return;
    _answers[questions[_currentIndex].id] = answer.trim();
    _currentIndex++;
  }

  /// Assembles all answers into a natural-language description
  /// suitable for passing to the LLM for JSON extraction.
  String buildRawDescription() {
    return [
      'Location: ${_answers['environment'] ?? 'unknown'}',
      'Injuries: ${_answers['injuries'] ?? 'none reported'}',
      'Resources available: ${_answers['resources'] ?? 'none'}',
      'Companions: ${_answers['companions'] ?? '0'} other people',
      'Primary goal: ${_answers['goal'] ?? 'survive'}',
    ].join('. ');
  }

  void reset() {
    _answers.clear();
    _currentIndex = 0;
  }
}

class AssessmentQuestion {
  final String id;
  final String text;
  final String hint;

  const AssessmentQuestion({
    required this.id,
    required this.text,
    required this.hint,
  });
}
