"""Build every artifact the Flutter app ships, in one pass.

There are four, and they only mean anything together: the index names the
passages, the vector file gives each one a position in embedding space, the
packed tokenizer lets the device put a query into that same space, and the
fixture pins the Dart tokeniser to the Python one that produced the vectors.

Building them separately is how they drift, so there is one command.
"""

from __future__ import annotations

import json
from pathlib import Path

from ..config import RetrievalConfig
from ..retrieval.tokenizer_pack import pack_tokenizer
from ..retrieval.tokenizer_ref import encode, read_packed
from .loader import export_index, load_corpus
from .vectors import export_vectors

# Deliberately awkward strings. A tokeniser that handles ordinary English and
# nothing else passes an eval and then mangles the first Hinglish query, so the
# fixture carries what the corpus and the golden sets actually contain:
# romanised Hindi, Devanagari, emoji, and whitespace that BPE treats specially.
FIXTURE_TEXTS: tuple[str, ...] = (
    "",
    " ",
    "  double  space  ",
    "\n\ttabs and newlines\n",
    "chest pain",
    "snake bite what to do",
    "task: search result | query: aag lag gayi hai",
    "title: none | text: Do not cut the bite or suck the venom.",
    "kutte ne kaata, haldi lagau kya",
    "baadh aa gayi hai kya karu",
    "सांप ने काटा क्या करूँ",
    "LPG cylinder leak in the kitchen",
    "ORS ka packet kaise banaye",
    "call 112 immediately",
    "🔥🐍 emoji and symbols ±§",
    "café naïve façade",
    "a" * 200,
)


def build_artifacts(
    tokenizer_json: Path,
    assets: Path,
    fixture: Path,
    *,
    config: RetrievalConfig,
) -> dict[str, Path]:
    """Write the index, the passage vectors, the tokenizer and the fixture.

    Args:
        tokenizer_json: Hugging Face ``tokenizer.json`` for the embedding
            model, the source the packed tokenizer is derived from.
        assets: The app's ``assets/index`` directory.
        fixture: Path for the Dart parity fixture, under ``test/fixtures``.
        config: Retrieval configuration; supplies the chunking policy and the
            embedding model, so the vectors match the index they ship beside.

    Returns:
        Artifact name to the path written.
    """
    corpus = load_corpus(cfg=config.chunking, passages=config.passages)

    index = export_index(corpus, assets / "corpus.json")
    vectors, manifest = export_vectors(
        corpus,
        assets / "passages.f32",
        model=config.embed_model,
        backend=config.embed_backend,
    )
    packed = pack_tokenizer(tokenizer_json, assets / "tokenizer.bin")
    written = write_fixture(packed, fixture)

    return {
        "index": index,
        "vectors": vectors,
        "vector_manifest": manifest,
        "tokenizer": packed,
        "fixture": written,
    }


def write_fixture(packed: Path, destination: Path) -> Path:
    """Write expected token ids for :data:`FIXTURE_TEXTS`.

    The Dart tokeniser is a second implementation of an algorithm whose output
    is invisible: a wrong split does not throw, it just produces a plausible
    vector in the wrong place, and retrieval quietly gets worse. Comparing ids
    against this fixture is the only cheap way to catch that.

    Args:
        packed: The packed tokenizer to encode with.
        destination: Output ``.json`` path; parent directories are created.

    Returns:
        The path written.
    """
    tokenizer = read_packed(packed)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        json.dumps(
            {
                "note": "generated by survive-rag pack; do not edit by hand",
                "cases": [
                    {"text": text, "ids": encode(text, tokenizer)}
                    for text in FIXTURE_TEXTS
                ],
            },
            ensure_ascii=False,
            indent=1,
        ),
        encoding="utf-8",
    )
    return destination
